### ISSUE TITLE
PrismaClientInitializationError: error: Error validating datasource `db`

### ISSUE THREAD

**Issue by bboysoulcn** [mikecao/umami#1192]
```bash
umami    | PrismaClientInitializationError: error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
umami    |   -->  schema.prisma:7
umami    |    | 
umami    |  6 |   provider = "postgresql"
umami    |  7 |   url      = env("DATABASE_URL")
```

```yaml
version: "3"
services: 
  umami:
    image: "ghcr.io/mikecao/umami:mysql-v1.32.1"
    container_name: "umami"
    restart: "always"
    environment: 
      - "DATABASE_URL=mysql://user:pass@10.0.0.12:3306/umami"
      - "DATABASE_TYPE=mysql"
      - "HASH_SALT="
    ports: 
      - "8084:3000"
```
