### ISSUE TITLE
cannot add website

### ISSUE THREAD

**Issue by Pcrab** [mikecao/umami#410]
I start umami through docker-compose with postgresql, all the settings are default.

It works all right, but when I try to add a website, it shows the following error.

umami_1          | PrismaClientKnownRequestError2: Query interpretation error. Error for binding '1': AssertionError("[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.")
umami_1          |     at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:79355:15)
umami_1          |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
umami_1          |   code: 'P2016',
umami_1          |   clientVersion: '2.12.1',
umami_1          |   meta: {
umami_1          |     details: `Error for binding '1': AssertionError("[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.")`
umami_1          |   }
umami_1          | }

**Comment by mikecao** [comment]
Did you pull all the code from the repo first?

**Comment by Pcrab** [comment]
I don't have all the repo on my machine, but have the sql folder, because I've read the docker-compose file and found it doesn't require other parts.

```
umami:
        image: ghcr.io/mikecao/umami:postgresql-latest
        environment:
            DATABASE_URL: postgresql://umami:umami@db:5432/umami
            DATABASE_TYPE: postgresql
            HASH_SALT: something
        depends_on:
            - db
    db:
        image: postgres:alpine
        environment:
          POSTGRES_DB: umami
          POSTGRES_USER: umami
          POSTGRES_PASSWORD: umami
        volumes:
          - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
          - umami-db-data:/var/lib/postgresql/data

volumes:
    umami-db-data:
```
