### ISSUE TITLE
BASE_PATH env in docker setup

### ISSUE THREAD

**Issue by sebastian-bartkowiak** [mikecao/umami#557]
Hi.

I just stumbled upon something strange. Reading docs and issues (#400 mostly) I was conviced that I should be able to serve umami from subdirectory from my docker-compose setup by passing `BASE_PATH` env variable, but I was not succesfull with that. After some debugging I discovered, that `BASE_PATH` env must be set to proper value prior to `npm run build` command, which is impossible to be done when using your prebuild docker container `ghcr.io/mikecao/umami` (since it already comes pre-built). Am I missing something obvious, is it a bug, or (for some reason) is it intended behaviour?

Cheers!

**Comment by gnarlex** [comment]
Hey there :) If it helps, you can change `docker-compose.yml` to build the docker image locally using the `dockerfile`. In `dockerfile` you could then add the `BASE_PATH` env variable.

Example of adjusted docker-compose file:
```yml
---
version: '3'
services:
  umami:
    build: ./ # <--- was 'image: ghcr.io/mikecao/umami:postgresql'
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
volumes:
  umami-db-data:
```

**Comment by sebastian-bartkowiak** [comment]
ok, thanks - that is some kind of workaround, because I guess it won't be easy (or even possible at all) to succesfully change this env variable after `npm run build`... thanks, will have to play around with that :)

**Comment by sebastian-bartkowiak** [comment]
ok, so I tried to set it up as you suggested, but still no luck.
first I just tried to set `BASE_PATH` like so:
```
umami:
        build:
            context: ./umami
        container_name: umami
        environment:
            - DATABASE_URL=postgresql://umami:umami@umami-db:5432/umami
            - DATABASE_TYPE=postgresql
            - HASH_SALT=some-random-string
            - BASE_PATH=/umami
        depends_on:
            - umami-db
        links:
            - umami-db
        ports:
            - 3000:3000
```
but it did not work (the container was being built but `BASE_DIR` was not respected). then I noticed, that setting `BASE_PATH` to a value ending with slash (for example `/umami/`) results in build error, so I used that to debug how those env variables are passed to build stage.
so:
```
umami:
        build:
            context: ./umami
        container_name: umami
        environment:
            - DATABASE_URL=postgresql://umami:umami@umami-db:5432/umami
            - DATABASE_TYPE=postgresql
            - HASH_SALT=some-random-string
            - BASE_PATH=/umami/
        depends_on:
            - umami-db
        links:
            - umami-db
        ports:
            - 3000:3000
```
no error raised
```
umami:
        build:
            context: ./umami
            args:
                - BASE_PATH=/umami/
        container_name: umami
        environment:
            - DATABASE_URL=postgresql://umami:umami@umami-db:5432/umami
            - DATABASE_TYPE=postgresql
            - HASH_SALT=some-random-string
            - BASE_PATH=/umami/
        depends_on:
            - umami-db
        links:
            - umami-db
        ports:
            - 3000:3000
```
also no error raised
the only way I was able to sucesfully pass `BASE_PATH` to build stage (and raise an error) was by creating `.env` file in main umami dir and putting `BASE_PATH=/umami/` there. so as far as I can see - there is no valid way to specify `BASE_PATH` via docker-compose. any ideas from here?

**Comment by sebastian-bartkowiak** [comment]
Just an update - I was not able to fully solve my issues with `BASE_PATH` so I gave up, switched to wildcard HTTPS certificate and served umami from subdomain.

**Comment by aep** [comment]
why is this closed? BASE_PATH isnt picked up from docker env

**Comment by tstanciu** [comment]
Same problem here. BASEPATH doesn't seem to work either with the docker image or with the local build :(

**Comment by tstanciu** [comment]
~~Same problem here. BASEPATH doesn't seem to work either with the docker image or with the local build :(~~

BASE_PATH works:
- Locally must be run every time "yarn build" + "yarn start" after modifying the ".env" file.
- For docker, the image must be built with the BASE_PATH ENV provided during the build. I think it is needed at the build time, and at runtime it becomes useless.
`docker image build --build-arg BASE_PATH=/umami-analytics -t "umami-app:1.0.1" .`

**Comment by fluoroom** [comment]
Sorry to necropost, but BASE_PATH is not being read while other envs are.

$ docker run -d --name umami --network umami_sql_network -e DATABASE_URL=postgresql://umami:umami@umami_db_1:5432/umami -e DATABASE_TYPE=postgresql -e BASE_PATH=/umami/ -p 127.0.0.1:3000:3000 docker.umami.is/umami-software/umami:postgresql-latest

$ docker logs umami
yarn run v1.22.22
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "umami", schema "public" at "umami_db_1:5432"ç

7 migrations found in prisma/migrations

No pending migrations to apply.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
   ▲ Next.js 15.0.4
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 173ms

**Comment by mqu** [comment]
hello everyone, I have been able to build a new Docker image for Umami, with BASE_PATH=/stats. 

Here is my docker-compose.yml / build section:
```
services:
  umami:
    # image: ghcr.io/umami-software/umami:postgresql-latest
    image: umami-custom:v2.17.0
    build:
       context: ./build/umami/src
       args:
        # - HTTP_PROXY=http://proxy:3128/
        # - HTTPS_PROXY=http://proxy:3128/
        # - http_proxy=http://proxy:3128/
        # - HTTPS_PROXY=http://proxy:3128/
        - DATABASE_TYPE=postgres
        - DATABASE_URL=postgresql://umami:umami@umami_db_1:5432/umami
        - BASE_URL=http://localhost:3000/stats/
        - BASE_PATH=/stats
```
- be careful : `DATABASE_TYPE` mus be `postgres` and not `postgresql` ; this is because of `scripts/copy-db-files.js` (https://github.com/umami-software/umami/blob/master/scripts/copy-db-files.js#L10).
- docker image won't build behind an HTTP-Proxy (#3327 issue)

to build, you need to clone Umami repository and checkout latest TAG : 
```
mkdir -p build/umami/src ;
( cd build/umami/src ; git clone https://github.com/umami-software/umami.git . ; git checkout v2.17.0)
```
- then run : `docker-compose build umami `; this will build `umami-custom:v2.17.0` Docker image.

Here is my Apache reverse-proxy configuration  that should work : 
```
        RewriteEngine On
        ProxyPreserveHost On
        RequestHeader set X-Forwarded-Proto https 

	# redirect to umami port ; must be before port 8929
	ProxyPass "/stats" "http://localhost:3000/stats"
	ProxyPassReverse "/stats" "http://localhost:3000/stats"

        # main application (wordpress instance)
        ProxyPass / http://localhost:8929/
        ProxyPassReverse / http://localhost:8929/
```
 - main application on https://wordpress.domain.com/
 - umami on sub URL : https://wordpress.domain.com/stats/
