### ISSUE TITLE
docker-compose postgres error - no pg_hba.conf entry for host

### ISSUE THREAD

**Issue by spadgeaki** [mikecao/umami#65]
Hello, thank you for great custom analytics tool. I wanted to boot it up using docker-compose, everything starts up just fine but when I try to login to default user account (admin/umami) I get following error

```
> umami@0.16.1 start /app
> next start

ready - started server on http://localhost:3000
PrismaClientUnknownRequestError: Error in connector: Error querying the database: db error: FATAL: no pg_hba.conf entry for host "192.168.122.1", user "umami", database "umami", SSL on
    at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:1:211253)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I tried creating custom `pg_hba.conf` with `host all all 0.0.0.0/0 trust` and attached it to database container

```
db:
    volumes:
      ...
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
```
but still no luck. I checked inside a running container and file is attached correctly.

**Comment by hugomd** [comment]
@spadgeaki Can you post the logs of the Postgres container please?

**Comment by spadgeaki** [comment]
This is combined log from docker-compose
```
Attaching to umami_umami_1, umami_db_1
umami_1  | 
umami_1  | > umami@0.16.1 start /app
umami_1  | > next start
umami_1  | 
umami_1  | ready - started server on http://localhost:3000
umami_1  | PrismaClientUnknownRequestError: Error in connector: Error querying the database: db error: FATAL: no pg_hba.conf entry for host "192.168.122.1", user "umami", database "umami", SSL on
umami_1  |     at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:1:211253)
umami_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2020-08-24 09:20:02.281 UTC [1] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
db_1     | 2020-08-24 09:20:02.281 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2020-08-24 09:20:02.282 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2020-08-24 09:20:02.399 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2020-08-24 09:20:02.635 UTC [25] LOG:  database system was shut down at 2020-08-24 09:19:42 UTC
db_1     | 2020-08-24 09:20:02.726 UTC [1] LOG:  database system is ready to accept connections
```

This is `docker-compose.yml`. I only tried adding that one line with config.

```
version: '3'
services:
  umami:
    build: .
    restart: unless-stopped
    ports:
      - "3111:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: fYj5vPe53mQ1z0Y94f$ghWElf22t9LoG528
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
volumes:
  umami-db-data:
```
