### ISSUE TITLE
Timed out fetching a new connection from the connection pool

### ISSUE THREAD

**Issue by zix99** [mikecao/umami#779]
I'm running the latest version from dockerhub, and after running for a few weeks, I start getting an unresponsive umami with an error-loop that looks like this:

```
yarn run v1.22.4
      
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]: Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool, Current connection limit: 5)
    at cb (/app/node_modules/@prisma/client/runtime/index.js:36374:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2024',
  clientVersion: '2.29.1',
  meta: { connection_limit: 5 }
}
PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]: Timed out fetching a new connection from the connection pool. (More info: http://pris.ly/d/connection-pool, Current connection limit: 5)
    at cb (/app/node_modules/@prisma/client/runtime/index.js:36374:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2024',
  clientVersion: '2.29.1',
  meta: { connection_limit: 5 }
}
... and so on ....
```

My compose (truncated) looks like this:
```
version: "3.5"

services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    networks:
      - default
      - traefik-net
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://umami:XXX@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: XXX
      IGNORE_IP: "XXX"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.umami.rule=Host(`XXX`)"
        - "traefik.http.services.umami.loadbalancer.server.port=3000"
        - "traefik.http.routers.umami.entrypoints=websecure"
      resources:
        limits: { cpus: '0.2', memory: '128M' }
        reservations: { cpus: '0.05', memory: '128M' }

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: XXX
    networks:
      - default
    configs:
      - source: umami-schema
        target: /docker-entrypoint-initdb.d/schema.postgresql.sql
    volumes:
      - umami-db:/var/lib/postgresql/data
    deploy:
      resources:
        limits: { cpus: '0.2', memory: '64M' }
        reservations: { cpus: '0.05', memory: '64M' }

<Truncated>
```

I'll try a few things, but figure I'd report an issue in case anyone has seen this before.
